#ifndef INCLUDES_CENTRALDATASTRUCTURE_INTERNALPROGRAMS_GLYCOPROTEINBUILDER_GLYCOPROTEINBUILDER_HPP
#define INCLUDES_CENTRALDATASTRUCTURE_INTERNALPROGRAMS_GLYCOPROTEINBUILDER_GLYCOPROTEINBUILDER_HPP

#include "includes/CentralDataStructure/InternalPrograms/GlycoproteinBuilder/glycosylationSite.hpp"
#include "includes/CentralDataStructure/InternalPrograms/GlycoproteinBuilder/gpInputStructs.hpp"
#include "includes/CentralDataStructure/InternalPrograms/GlycoproteinBuilder/glycoproteinOverlapResolution.hpp"
#include "includes/CentralDataStructure/Readers/Pdb/pdbPreprocessorInputs.hpp"
#include "includes/CentralDataStructure/Overlaps/overlaps.hpp"
#include <string>

using cds::Assembly;

class GlycoproteinBuilder
{
  public:
    //////////////////////////////////////////////////////////
    //                       CONSTRUCTOR                    //
    //////////////////////////////////////////////////////////
    GlycoproteinBuilder(glycoprotein::GlycoproteinBuilderInputs inputStruct,
                        pdb::PreprocessorOptions preprocessingOptions = pdb::PreprocessorOptions());

    //////////////////////////////////////////////////////////
    //                       ACCESSOR                       //
    //////////////////////////////////////////////////////////
    inline Assembly* getGlycoprotein()
    {
        return &glycoprotein_;
    }

    //////////////////////////////////////////////////////////
    //                       MUTATOR                        //
    //////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////////
    //                       FUNCTIONS                      //
    //////////////////////////////////////////////////////////
    void ResolveOverlaps();
    void WritePdbFile(const std::string prefix = "glycoprotein", const bool writeConectSection = true);
    void WriteOffFile(const std::string prefix = "glycoprotein");
    // void WriteOutputFiles(std::string prefix = "Glycoprotein_All_Resolved");
    void PrintDihedralAnglesAndOverlapOfGlycosites();

  private:
    //////////////////////////////////////////////////////////
    //                  PRIVATE ACCESSORS                   //
    //////////////////////////////////////////////////////////
    inline std::vector<GlycosylationSite>& GetGlycosites()
    {
        return glycosites_;
    }

    inline unsigned int GetOverlapTolerance() const
    {
        return overlapTolerance_;
    }

    inline int GetNumberOfStructuresToOutput() const
    {
        return structuresToOutput_;
    }

    inline int GetNumberOfOuputtedStructures() const
    {
        return totalOutputtedStrucures_;
    }

    inline int GetPersistCycles() const
    {
        return persistCycles_;
    }

    inline bool GetIsDeterministic() const
    {
        return isDeterministic_;
    }

    //////////////////////////////////////////////////////////
    //                  PRIVATE MUTATORS                    //
    //////////////////////////////////////////////////////////

    inline void SetPersistCycles(const int i)
    {
        persistCycles_ = i;
    }

    inline void SetOverlapTolerance(const unsigned int i)
    {
        overlapTolerance_ = i;
    }

    inline void SetProteinPDBFileName(const std::string s)
    {
        proteinPDBFileName_ = s;
    }

    inline void SetStructuresToOutput(const int i)
    {
        structuresToOutput_ = i;
    }

    inline void SetIsDeterministic(const bool b)
    {
        isDeterministic_ = b;
    }

    inline void incrementOutputtedStructures()
    {
        ++totalOutputtedStrucures_;
    }

    //////////////////////////////////////////////////////////
    //                  PRIVATE FUNCTIONS                   //
    //////////////////////////////////////////////////////////
    // Class instantiation
    void CreateGlycosites(const std::vector<glycoprotein::GlycositeInput> glycositesInputVector);
    Residue* SelectResidueFromInput(const std::string userSelection);
    //////////////////////////////////////////////////////////
    //                       ATTRIBUTES                     //
    //////////////////////////////////////////////////////////
    std::vector<GlycosylationSite> glycosites_; // Info about each glycosylation site. See the class.
    std::vector<Residue*> proteinResidues_;
    Assembly glycoprotein_; // Generated by this code.
    ResiduesByType overlapResidues_;
    unsigned int overlapTolerance_ = 1; // What amount of overlap to tolerate.
    std::string proteinPDBFileName_;    // The protein pdb file to attach the glycans to.
    int structuresToOutput_      = 1;   // Number of output 3D structures. Default 1.
    int totalOutputtedStrucures_ = 0;
    int persistCycles_    = 5;     // Algos continue for persistCycles, reset count if there is an overlap improvement.
    bool isDeterministic_ = false; // "true" is good for testing: always same output.
};

#endif
