#ifndef INCLUDES_CENTRALDATASTRUCTURE_INTERNALPROGRAMS_GLYCOPROTEINBUILDER_GLYCOPROTEINBUILDER_HPP
#define INCLUDES_CENTRALDATASTRUCTURE_INTERNALPROGRAMS_GLYCOPROTEINBUILDER_GLYCOPROTEINBUILDER_HPP

#include "includes/CentralDataStructure/InternalPrograms/GlycoproteinBuilder/glycosylationSite.hpp"
#include "includes/CentralDataStructure/InternalPrograms/GlycoproteinBuilder/gpInputStructs.hpp"
#include "includes/CentralDataStructure/InternalPrograms/GlycoproteinBuilder/glycoproteinOverlapResolution.hpp"
#include "includes/CentralDataStructure/Readers/Pdb/pdbPreprocessorInputs.hpp"
#include "includes/CentralDataStructure/Geometry/overlap.hpp"
#include <string>

using cds::Assembly;

class GlycoproteinBuilder
{
  public:
    GlycoproteinBuilder(glycoprotein::GlycoproteinBuilderInputs inputStruct,
                        pdb::PreprocessorOptions preprocessingOptions = pdb::PreprocessorOptions());

    inline Assembly* getGlycoprotein()
    {
        return &glycoprotein_;
    }

    void ResolveOverlaps(std::string outputDir);

  private:
    std::vector<GlycosylationSite> glycosites_; // Info about each glycosylation site. See the class.
    std::vector<Residue*> proteinResidues_;
    Assembly glycoprotein_; // Generated by this code.
    glycoprotein::GlycoproteinBuilderInputs settings;
};

#endif
